// Markup for the painted bamboo scene (images are generated by build.mjs from src/scenery.mjs).
const img = (root, name, cls, extra = "") =>
  `<img class="${cls}" src="${root}assets/img/scene/${name}.svg" alt="" width="900" height="1000" decoding="async"${extra} />`;

export function groveLayers(root, { middle = "" } = {}) {
  return `
    ${img(root, "sky", "g-sky", ' fetchpriority="high"')}
    <div class="g-curtain g-far g-l">${img(root, "curtain-far-l", "g-img")}</div>
    <div class="g-curtain g-far g-r">${img(root, "curtain-far-r", "g-img")}</div>
    ${middle}
    <div class="g-curtain g-near g-l"><div class="g-sway">${img(root, "curtain-near-l", "g-img", ' fetchpriority="high"')}</div></div>
    <div class="g-curtain g-near g-r"><div class="g-sway g-sway--r">${img(root, "curtain-near-r", "g-img", ' fetchpriority="high"')}</div></div>
    <img class="g-ground" src="${root}assets/img/scene/ground.svg" alt="" width="1200" height="200" decoding="async" />`;
}

export function shore(root) {
  return `<div class="shore" aria-hidden="true"><img src="${root}assets/img/scene/shore.svg" alt="" width="1200" height="360" loading="lazy" decoding="async" /></div>`;
}

// a few lily pads and koi drifting in the water behind the content (CSS-animated, GPU-only)
export function pondDecor() {
  const pads = [
    [6, 4, 74, "#c9946c"], [80, 9, 56, "#8ea1a8"], [64, 22, 44, "#9a9a96"], [10, 33, 60, "#8ea1a8"],
    [84, 46, 70, "#c9946c"], [4, 58, 50, "#9a9a96"], [72, 70, 58, "#8ea1a8"], [14, 84, 66, "#c9946c"], [78, 93, 48, "#9a9a96"],
  ].map(([x, y, s, c]) => `<svg class="p-pad" style="left:${x}%;top:${y}%;width:${s}px;height:${s}px;color:${c}"><use href="#pad"/></svg>`).join("");
  const koi = [
    ["a", 12, 46], ["b", 41, 58], ["a", 67, 52], ["b", 88, 64],
  ].map(([dir, top, dur], i) => `<div class="swimmer swimmer--${dir}" style="top:${top}%;animation-duration:${dur}s;animation-delay:-${i * 11}s"><svg class="swimmer__koi" viewBox="0 0 120 50"><use href="#koi"/></svg></div>`).join("");
  return `<div class="pond-decor" aria-hidden="true">${pads}${koi}</div>`;
}
