import { PETAL, LEAF_PATH } from "../scenery.mjs";

// Markup for the painted bamboo scene (images are generated by build.mjs from src/scenery.mjs).
const img = (root, name, cls, extra = "") =>
  `<img class="${cls}" src="${root}assets/img/scene/${name}.svg" alt="" width="900" height="1000" decoding="async"${extra} />`;

// deterministic "random" so builds are stable
const jitter = (i, k) => ((Math.sin(i * 12.9898 + k * 78.233) * 43758.5453) % 1 + 1) % 1;

function clouds() {
  return `<div class="jp-clouds">${[0, 1, 2, 3].map((i) =>
    `<div class="jp-cloud" style="top:${(14 + i * 9 + jitter(i, 1) * 5).toFixed(1)}%;width:${(38 + jitter(i, 2) * 24).toFixed(0)}vw;animation-duration:${(70 + jitter(i, 3) * 40).toFixed(0)}s;animation-delay:-${(jitter(i, 4) * 100).toFixed(0)}s"></div>`).join("")}</div>`;
}

function petals(n) {
  let out = "";
  for (let i = 0; i < n; i++) {
    const leaf = i % 4 === 3;
    const art = leaf
      ? `<svg viewBox="-2 -10 82 20" width="${(20 + jitter(i, 5) * 8).toFixed(0)}" height="8" aria-hidden="true"><path d="${LEAF_PATH}" fill="#5b6853" fill-opacity=".75"/></svg>`
      : `<svg viewBox="-8 -20 22 22" width="${(10 + jitter(i, 5) * 5).toFixed(0)}" height="12" aria-hidden="true"><path d="${PETAL}" fill="${["#f4c3ca", "#efb2bc", "#f8d6db"][i % 3]}"/></svg>`;
    out += `<div class="falling-leaf" style="left:${(jitter(i, 6) * 100).toFixed(1)}%;animation-duration:${(12 + jitter(i, 7) * 8).toFixed(1)}s;animation-delay:-${(jitter(i, 8) * 20).toFixed(1)}s"><div class="falling-leaf__inner" style="animation-duration:${(2.4 + jitter(i, 9) * 1.6).toFixed(1)}s">${art}</div></div>`;
  }
  return `<div class="g-petals">${out}</div>`;
}

/* The bamboo grove, in the same ink style as the Veg menu: sky with temples, clouds,
   a pale back grove, mist, two independently swaying foreground layers per side,
   a cherry-blossom branch and falling petals. */
export function groveLayers(root, { middle = "" } = {}) {
  return `
    ${img(root, "sky", "g-sky", ' fetchpriority="high"')}
    ${clouds()}
    <div class="g-curtain g-far g-l"><div class="g-sway g-sway--back">${img(root, "curtain-back-l", "g-img")}</div></div>
    <div class="g-curtain g-far g-r"><div class="g-sway g-sway--back">${img(root, "curtain-back-r", "g-img")}</div></div>
    ${middle}
    <div class="jp-mist"></div>
    <div class="g-curtain g-near g-l"><div class="g-sway g-sway--a">${img(root, "curtain-near-a-l", "g-img", ' fetchpriority="high"')}</div><div class="g-sway g-sway--b">${img(root, "curtain-near-b-l", "g-img")}</div></div>
    <div class="g-curtain g-near g-r"><div class="g-sway g-sway--a">${img(root, "curtain-near-a-r", "g-img", ' fetchpriority="high"')}</div><div class="g-sway g-sway--b">${img(root, "curtain-near-b-r", "g-img")}</div></div>
    <img class="sakura sakura--right" src="${root}assets/img/scene/sakura.svg" alt="" width="320" height="180" decoding="async" />
    <img class="g-ground" src="${root}assets/img/scene/ground.svg" alt="" width="1200" height="200" decoding="async" />
    ${petals(12)}`;
}

export function shore(root) {
  return `<div class="shore" aria-hidden="true"><img src="${root}assets/img/scene/shore.svg" alt="" width="1200" height="360" loading="lazy" decoding="async" /></div>`;
}

// a few lily pads and koi drifting in the water behind the content (CSS-animated, GPU-only)
export function pondDecor() {
  const pads = [
    [6, 4, 74, "#c9946c"], [80, 9, 56, "#8ea1a8"], [64, 22, 44, "#9a9a96"], [10, 33, 60, "#8ea1a8"],
    [84, 46, 70, "#c9946c"], [4, 58, 50, "#9a9a96"], [72, 70, 58, "#8ea1a8"], [14, 84, 66, "#c9946c"], [78, 93, 48, "#9a9a96"],
  ].map(([x, y, s, c]) => `<svg class="p-pad" style="left:${x}%;top:${y}%;width:${s}px;height:${s}px;color:${c}"><use href="#pad"/></svg>`).join("");
  const koi = [
    ["a", 12, 46], ["b", 41, 58], ["a", 67, 52], ["b", 88, 64],
  ].map(([dir, top, dur], i) => `<div class="swimmer swimmer--${dir}" style="top:${top}%;animation-duration:${dur}s;animation-delay:-${i * 11}s"><svg class="swimmer__koi" viewBox="0 0 120 50"><use href="#koi"/></svg></div>`).join("");
  return `<div class="pond-decor" aria-hidden="true">${pads}${koi}</div>`;
}
