import { PETAL, LEAF_PATH } from "../scenery.mjs";

// Markup for the painted bamboo scene (images are generated by build.mjs from src/scenery.mjs).
const img = (root, name, cls, extra = "") =>
  `<img class="${cls}" src="${root}assets/img/scene/${name}.svg" alt="" width="900" height="1000" decoding="async"${extra} />`;

// deterministic "random" so builds are stable
const jitter = (i, k) => ((Math.sin(i * 12.9898 + k * 78.233) * 43758.5453) % 1 + 1) % 1;

// Japanese-screen clouds drifting across the sky (pre-drawn images, moved by the compositor)
function clouds(root) {
  const set = [["a", 9, 64, 120, 10], ["c", 22, 52, 150, 70], ["b", 31, 70, 135, 35], ["a", 4, 44, 170, 100]];
  return `<div class="jp-clouds">${set.map(([v, top, w, dur, delay]) =>
    `<img class="kumo" src="${root}assets/img/scene/cloud-${v}.svg" alt="" width="420" height="120" decoding="async" style="top:${top}%;width:${w}vw;animation-duration:${dur}s;animation-delay:-${delay}s" />`).join("")}</div>`;
}

function petals(n) {
  let out = "";
  for (let i = 0; i < n; i++) {
    const leaf = i % 4 === 3;
    const art = leaf
      ? `<svg viewBox="-2 -10 82 20" width="${(20 + jitter(i, 5) * 8).toFixed(0)}" height="8" aria-hidden="true"><path d="${LEAF_PATH}" fill="#5b6853" fill-opacity=".75"/></svg>`
      : `<svg viewBox="-8 -20 22 22" width="${(10 + jitter(i, 5) * 5).toFixed(0)}" height="12" aria-hidden="true"><path d="${PETAL}" fill="${["#f4c3ca", "#efb2bc", "#f8d6db"][i % 3]}"/></svg>`;
    out += `<div class="falling-leaf" style="left:${(jitter(i, 6) * 100).toFixed(1)}%;animation-duration:${(12 + jitter(i, 7) * 8).toFixed(1)}s;animation-delay:-${(jitter(i, 8) * 20).toFixed(1)}s"><div class="falling-leaf__inner" style="animation-duration:${(2.4 + jitter(i, 9) * 1.6).toFixed(1)}s">${art}</div></div>`;
  }
  return `<div class="g-petals">${out}</div>`;
}

/* Home page grove, in two parts.
   groveBack: the far scene (sky with temples, clouds, the pale back grove, mist, petals).
     It is pinned while you scroll through the grove and drifts up slowly.
   groveFront: the tall foreground bamboo, which scrolls with the page like a camera
     panning down the stalks while they part to show the card behind them. */
export function groveBack(root) {
  return `
    ${img(root, "sky-plain", "g-sky")}
    ${clouds(root)}
    <img class="g-hills" src="${root}assets/img/scene/hills.svg" alt="" width="1000" height="620" decoding="async" />
    <div class="g-curtain g-far g-l"><div class="g-sway g-sway--back">${img(root, "tall-back-l", "g-img")}</div></div>
    <div class="g-curtain g-far g-r"><div class="g-sway g-sway--back">${img(root, "tall-back-r", "g-img")}</div></div>
    <div class="jp-mist"></div>
    ${petals(12)}`;
}

export function groveFront(root, { hero, reveal }) {
  const near = (side) =>
    `<div class="g-curtain g-near g-${side}" aria-hidden="true"><div class="g-sway g-sway--a">${img(root, `tall-near-a-${side}`, "g-img", ' fetchpriority="high"')}</div><div class="g-sway g-sway--b">${img(root, `tall-near-b-${side}`, "g-img")}</div></div>`;
  return `
    <div class="reveal-wrap">${reveal}</div>
    ${near("l")}
    ${near("r")}
    <img class="sakura sakura--right" src="${root}assets/img/scene/sakura.svg" alt="" width="320" height="180" decoding="async" aria-hidden="true" />
    <img class="g-ground" src="${root}assets/img/scene/ground.svg" alt="" width="1200" height="200" decoding="async" aria-hidden="true" />
    <div class="hero-wrap">${hero}</div>`;
}

/* A shorter, already-parted grove that frames a panel (events page). */
export function groveLayers(root) {
  return `
    ${img(root, "sky", "g-sky", ' fetchpriority="high"')}
    ${clouds(root)}
    <div class="g-curtain g-far g-l"><div class="g-sway g-sway--back">${img(root, "curtain-back-l", "g-img")}</div></div>
    <div class="g-curtain g-far g-r"><div class="g-sway g-sway--back">${img(root, "curtain-back-r", "g-img")}</div></div>
    <div class="jp-mist"></div>
    <div class="g-curtain g-near g-l"><div class="g-sway g-sway--a">${img(root, "curtain-near-a-l", "g-img", ' fetchpriority="high"')}</div><div class="g-sway g-sway--b">${img(root, "curtain-near-b-l", "g-img")}</div></div>
    <div class="g-curtain g-near g-r"><div class="g-sway g-sway--a">${img(root, "curtain-near-a-r", "g-img", ' fetchpriority="high"')}</div><div class="g-sway g-sway--b">${img(root, "curtain-near-b-r", "g-img")}</div></div>
    <img class="sakura sakura--right" src="${root}assets/img/scene/sakura.svg" alt="" width="320" height="180" decoding="async" />
    <img class="g-ground" src="${root}assets/img/scene/ground.svg" alt="" width="1200" height="200" decoding="async" />
    ${petals(12)}`;
}

export function shore(root) {
  return `<div class="shore" aria-hidden="true"><img src="${root}assets/img/scene/shore.svg" alt="" width="1200" height="360" loading="lazy" decoding="async" /></div>`;
}
